permalink: /:year:month:day/:title
url: https://BaldDurumy.github.io
baseurl: ""

# variables
name: BaldDurumy
description: Your description here
google_verification: null


# File management
include: [".htaccess", "_posts"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
